config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: 'users#index'
resources :users
resources :accounts
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :accounts, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.all
  end

  def show
    @account = Account.find(params[:id])
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)

    redirect_to account_path(@account)
  end

  def update
    @account = Account.find(params[:account_id])
    @account.spent_funds += params[:Account].to_f
    @account.remaining_funds -= params[:Account].to_f
    @account.save
    redirect_to user_path(params[:user_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.create!(user_params)

    redirect_to user_path(@user)
  end

  def new
    @user = User.new
  end

  def update
    @user = User.find(params[:user_id])
    @user.accounts << Account.create(remaining_funds: params[:Transportation], spent_funds: 0, name: 'Transportation')
    @user.accounts << Account.create(remaining_funds: params[:Groceries], spent_funds: 0, name: 'Groceries')
    @user.accounts << Account.create(remaining_funds: params[:Bills], spent_funds: 0, name: 'Bills')
    @user.accounts << Account.create(remaining_funds: params[:Entertainment], spent_funds: 0, name: 'Entertainment')
    @user.accounts << Account.create(remaining_funds: params['Dining Out'], spent_funds: 0, name: 'Dining Out')
    @user.accounts << Account.create(remaining_funds: params[:Shopping], spent_funds: 0, name: 'Shopping')
    @user.save
    redirect_to user_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :total_funds)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/index.html.erb
<h1>Account</h1>

<% @accounts.each do |account| %>
  <div>
    <%= account.name %>
  </div>
<% end %>

app/views/accounts/new.html.erb
<%= f.label "Budgeted Amount" %>
<%= f.text_field :remaining_funds %>

app/views/accounts/show.html.erb
<h1><%= @account.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budgit!</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href='https://fonts.googleapis.com/css?family=Chicle')>
  </head>

  <body>
  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
  </body>
</html>

app/views/users/index.html.erb
<div class = "container">
<h1>Welcome to Budgit!</h1>
<%= link_to "Create an account", new_user_path %>
<ul>
  <% @users.each do |user| %>
      <li><%= link_to user.email, user_path(user) %></li>
  <% end %>
</ul>
</div>

app/views/users/new.html.erb
<h1>New User</h1>
<%= form_for @user do |f| %>
  <%= f.label "Please enter your email address" %>
  <%= f.text_field :email %> <br>
  <%= f.label "Create a password" %>
  <%= f.password_field :password %> <br>
  <%= f.label "Confirm your password" %>
  <%= f.password_field :password_confirmation %> <br>
  <%= f.label "Enter your estimated monthly budget" %>
  <%= f.text_field :total_funds %> <br>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1 id= 'test'><%= @user.email %></h1>
<h3><%=link_to "Sign Out", new_user_path %></h3>
<h2>Your remaining budget is currently at $<%= number_with_precision (@user.total_funds - @user.accounts.map(&:spent_funds).inject(0, &:+)), :precision => 2 %></h2>
<% if @user.accounts.any? %>
  <h2>Enter your expense</h2>
  <% @user.accounts.sort_by{|acc| acc.name }.each do |account| %>
  <%= form_tag('/accounts/update', :method => :put) do %>
    <%= text_field_tag 'Account' %>
    <%= hidden_field_tag 'account_id', account.id %>
    <%= hidden_field_tag 'user_id', @user.id %>
    <%= submit_tag "Update" %>
  <% end %>
    <div><%= account.name %>: $<%= number_with_precision account.remaining_funds, :precision => 2 %></div>
  <% end %>
<% else %>
  <h2>Create your budget</h2>
  <%= form_tag('/users/update', :method => :put) do %>
      <%= label_tag 'Transportation' %><br>
      <%= text_field_tag 'Transportation' %><br>
      <%= label_tag 'Groceries' %><br>
      <%= text_field_tag 'Groceries' %><br>
      <%= label_tag 'Bills' %><br>
      <%= text_field_tag 'Bills' %><br>
      <%= label_tag 'Entertainment' %><br>
      <%= text_field_tag 'Entertainment' %><br>
      <%= label_tag 'Dining Out' %><br>
      <%= text_field_tag 'Dining Out' %><br>
      <%= label_tag 'Shopping' %><br>
      <%= text_field_tag 'Shopping' %><br>
      <%= hidden_field_tag 'user_id', @user.id %>
      <%= submit_tag "Submit" %>
  <% end %>
<% end %>